### ISSUE TITLE
Is this alive and good for production?

### ISSUE THREAD

**Issue by keligijus** [Shopify/graphql-js-client#136]
It seems that activity is sparse on this repo.

2 PRs that seem abandoned and are over a year old.

Any advice on the best approach to use  Storefront API GraphQL?

**Comment by swalkinshaw** [comment]
Activity is sparse because this project is basically "done" 😄 

This library powers our https://github.com/Shopify/js-buy-sdk as well which is used in production by a lot of merchants.

But one benefit of GraphQL is that you can use *any* client with any GraphQL API including our Storefront API. Here are some popular clients: https://github.com/chentsulin/awesome-graphql#clients

**Comment by keligijus** [comment]
Awesome 😄  thanks very much for clarification @swalkinshaw!
