### ISSUE TITLE
README does not specify project objective or difference with Relay

### ISSUE THREAD

**Issue by tarikjn** [Shopify/graphql-js-client#96]
This project claims to be a "A Relay compliant GraphQL client", but there is no information for an uninformed reader to understand why it was created or how it differs from Relay. I, for one, am still looking for an answer to these questions.

**Comment by minasmart** [comment]
Relay is a set of add on specifications ([object identification](https://facebook.github.io/relay/graphql/objectidentification.htm), [connections](https://facebook.github.io/relay/graphql/connections.htm), & [mutations](https://facebook.github.io/relay/graphql/mutations.htm)) to GraphQL. If you're asking how this project differs from Relay: this is a piece of client code and not a specification. We use that specification to inform how we built our client, and how best to comply with the rules set forth by the spec. You are likely referring to [Relay the javascript framework](https://facebook.github.io/relay/), which confusingly shares the same name.

Our goal is not to educate individuals on the use of GraphQL. There's a significant amount of information out there already, and there's no point in duplicating that. I'd recommend starting with the [full stack graphql tutorial](https://www.howtographql.com/).

If you're curious about why this project exists, it's so that we could write code that supports relay spec features, but wasn't bound to a particular UI framework. This is not something that exists elsewhere. If you want to bundle GraphQL client code into a library, or use it server-to-server, you can't use the Relay javascript framework, or Apollo client to do that.

Hope this helps to answer your questions.

**Comment by tarikjn** [comment]
Thank you very much for this detailed clarification @minasmart
